# Generated by Django 3.2.11 on 2025-07-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-_time'], 'verbose_name': 'Client Database', 'verbose_name_plural': 'Clients Database'},
        ),
    ]
