# Generated by Django 5.1.3 on 2025-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
